### ISSUE TITLE
Про оформление кода

### ISSUE THREAD

**Issue by bonvech** [Mendaliz/Gallows#1]
Комментарии лучше писать с таким же отступом, что и комментируемый кусок кода.

https://github.com/Mendaliz/Gallows/blob/79ae06ac80860e1a12e5c9ff1067b7cf727672d7/Gallows.py#L76
здесь тоже лучше использовать отступы для улучшения читаемости.

Хорошо бы прокомментировать назначение некоторых переменных.

Есть опечатки в тексте на русском языке.

**Comment by Mendaliz** [comment]
Corrected everything what found.
